trigger:
- master
- v*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install fsharp
    displayName: 'Install F#'
  - task: UseDotNet@2
    displayName: Stick with .NET Core SDK version compatible to Mono toolchain
    inputs:
      version: 3.1.101
  - script: ./build.sh Test
  - task: CopyFiles@1
    inputs:
      contents: ./build_output/?(*.nupkg|*.snupkg)
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Linux
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/**/*.trx'
      testRunTitle: '$(Agent.JobName)'

- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - task: UseDotNet@2
    inputs:
      version: 3.1.101
  - script: ./azure-pipeline-osx-setup.sh
  - script: ./build.sh Test
  - task: CopyFiles@1
    inputs:
      contents: ./build_output/?(*.nupkg|*.snupkg)
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: macOS
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/**/*.trx'
      testRunTitle: '$(Agent.JobName)'

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    inputs:
      version: 3.1.101
  - script: choco install gtksharp
  - script: .\build.cmd Test
  - task: CopyFiles@2
    inputs:
      contents: build_output\?(*.nupkg|*.snupkg)
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Windows
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/**/*.trx'
      testRunTitle: '$(Agent.JobName)'