name: .NET (Pull Request)
on: pull_request

jobs:
  build:
    runs-on: macos-latest
    env:
      SLN_FILE: Fabulous-NoSamples.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.200
    - name: Check code formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check -r src samples templates
    - name: Install dotnet workload
      run: dotnet workload install ios android
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${SLN_FILE}
    - name: Test
      run: dotnet test --no-build --configuration Release ${SLN_FILE}
